service: foodfinder

frameworkVersion: '2'

provider:
  name: azure
  runtime: nodejs12
  region: 'Australia Southeast'  
  stage: ${opt:stage, 'dev'}  

plugins: 
  - serverless-azure-functions

package:
  exclude:
    - local.settings.json
    - .vscode/**

functions:
  getNearestFoodtrucks:
    handler: src/handlers/getNearestFoodtrucks.handler
    events:
      - http: true
        methods:
          - GET
        route: foodtrucks/nearest
        authLevel: anonymous # can also be `function` or `admin`
